name: db
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  stormberry: ^0.13.1
  json_annotation: ^4.6.0
  meta: ^1.7.0
  equatable: ^2.0.3
  dartz: ^0.10.1
  freezed_annotation: ^2.2.0
  dart_frog: ^0.3.4

dev_dependencies:
  build_runner: ^2.3.3
  json_serializable: ^6.3.1
  mocktail: ^1.0.0
  lints: ^2.0.0
  test: ^1.21.0

