import 'package:stormberry/stormberry.dart';

// Will be generated by stormberry
part 'users_model.schema.dart';

@Model()
abstract class User {
  @PrimaryKey()
  String get id;

  String get name;
}
